# Generated by Django 2.1.4 on 2018-12-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='projector_availability',
            new_name='is_projector_available',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room')},
        ),
    ]
